// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlite

import (
	"database/sql"
	"time"
)

type Event struct {
	ID          int64
	SessionID   string
	EventName   string
	Url         string
	Referrer    sql.NullString
	UtmSource   sql.NullString
	UtmMedium   sql.NullString
	UtmCampaign sql.NullString
	UtmTerm     sql.NullString
	UtmContent  sql.NullString
	CreatedAt   time.Time
}

type Prop struct {
	ID        int64
	EventID   int64
	Key       string
	Value     string
	CreatedAt time.Time
}

type Revenue struct {
	ID        int64
	EventID   int64
	Key       string
	Value     string
	CreatedAt time.Time
}

type Session struct {
	ID         string
	Language   sql.NullString
	Country    sql.NullString
	Browser    sql.NullString
	Os         sql.NullString
	ScreenType sql.NullString
	CreatedAt  time.Time
}
